// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSErzwYGPAMFt_Fth4Ey8eAjji_BAdEJQ',
    appId: '1:322778753757:web:8b5c7e877a282a4b524934',
    messagingSenderId: '322778753757',
    projectId: 'safaisathi-febc9',
    authDomain: 'safaisathi-febc9.firebaseapp.com',
    storageBucket: 'safaisathi-febc9.appspot.com',
    measurementId: 'G-QT1966K4R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3kEg8B2kbnCxLVg_rCJJhUEZMYSCyhI',
    appId: '1:322778753757:android:da2f26b857c8e796524934',
    messagingSenderId: '322778753757',
    projectId: 'safaisathi-febc9',
    storageBucket: 'safaisathi-febc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5xmZFGDFIN4aX18ylk5qMS8jBncyzIiI',
    appId: '1:464366207317:ios:fdd53ca17ba4fc2a63efdc',
    messagingSenderId: '464366207317',
    projectId: 'vibecheck-74652',
    storageBucket: 'vibecheck-74652.appspot.com',
    iosBundleId: 'com.example.eventappFrontend',
  );
}